const enStrings = {
  'appTitle': 'ALphaLog',
  'commonError': 'Something went wrong',
  'loginTitle': 'Login',
  'detailDeliveryTitle': 'Detail Trip',
  'listDeliveryTitle': 'Delivery list',
  'demo': 'Demo Page',
  'all': 'All',
  'finishedDelivery': 'Finished Delivery',
  'pending': 'Pending',
  'waiting': 'Waiting',
  'vehicleNumber': 'Vehicle Number',
  'deliveryCode': 'Delivery Code',
  'seeDetail': 'See Detail',
  'batchBrowsing': 'Batch Browsing',
  'setDate': 'Set Date',
  'SGF': 'SGF',
  'pickUpLocationTitle': 'Pick up location',
  'placeOfDeleveryTitle': 'Place of delivery',
  'notyfiComeTitle': 'notyfiComeTitle...',
  'receivedTitle': 'receivedTitle...',
  'registerTitle' : 'Register',
  'forgotPasswordTitle': 'Forgot password?',
  'phoneNumber': 'Phone number',
  'password': 'Password',
  'errorPhoneNumber': 'Invalid your phone number',
  'errorPassword': 'Password minimum 6 characters',
  'loading': 'Loading...',
  'errorLoading': 'Wrong username or password!',
  'confirm': 'Confirm',
  'back': 'Back',
  'batchBrowsingConfirmation': 'Batch Browsing Confirmation?',
  'pleaseSelectCustomer': 'Please select a customer to browse',
  'selectCustomer': 'Select a customer',
  'filterAndSearch': 'Filter And Search',
  'pleaseInputKeyWord': 'Please Enter Key Word',
  'fromDate': 'From Date',
  'toDate': 'To Date',
  'complete': 'Complete',
  'listDrivers': 'List drivers',
  'listCar': 'List cars',
  'detailTitle': 'Detail',

  'modifyProfile': 'Modify profile',
  'changeVehicle': 'Change vehicle',
  'notification': 'Notification',
  'logout': 'Logout',
  'manageDeliveryTitle': 'Manage Delivery',
  'cancel': 'Cancel',
  'end': 'End',
  'tracking': 'Tracking',
  'update': 'Update',

  'deliveryDate': 'Delivery Date',
  'receivedDate': 'Received Date',
  'customer': 'Customer',

  'hintTextFieldSearch': 'Customers, Operations,...',
  'filterFollow': 'Filter follow',
  'tripNotCreated': 'Trip not created',
  'receivedGoods': 'Received goods',
  'feeApproved': 'Fee approved',
  'tripApproved': 'Trip approved',
  'denied': 'Denied',
  'delivered': 'Delivered',
  'noNewTripDriver': 'Currently, you do not have a flight. Please create a trip to view information',
  'history': 'History',
  'editInformation': 'Edit information',

  'firstNameAndLastName': 'First and last name',
  'birthday': 'Birthday',
  'email': 'Email',
  'identityCard': 'Identity Card',
};
