const viStrings = {
  'appTitle': 'AlphaLog',
  'commonError': 'Đã có lỗi xảy ra',
  'loginTitle': 'Đăng nhập',
  'detailDeliveryTitle': 'Thông tin Chuyến',
  'listDeliveryTitle': 'Danh sách chuyến',
  'demo': 'Demo Page',
  'all': 'Tất cả ',
  'finishedDelivery': 'Giao xong',
  'pending': 'Chờ duyệt',
  'waiting': 'Đang chờ',
  'vehicleNumber': 'Số xe',
  'deliveryCode': 'Mã chuyến',
  'seeDetail': 'Xem chi tiết',
  'batchBrowsing': 'Duyệt hàng loạt',
  'setDate': 'Ngày set',
  'SGF': 'SGF',
  'pickUpLocationTitle': 'Điểm nhận',
  'placeOfDeleveryTitle': 'Điểm giao',
  'notyfiComeTitle': 'Báo đến',
  'receivedTitle': 'Nhận xong',
  'registerTitle': 'Đăng kí',
  'forgotPasswordTitle': 'Quên mật khẩu?',
  'phoneNumber': 'Số điện thoại',
  'password': 'Mật khẩu',
  'errorPhoneNumber': 'Số điện thoại không hợp lệ',
  'errorPassword': 'Mật khẩu tối thiểu 6 kí tự',
  'loading': 'Loading...',
  'errorLoading': 'Sai Tên đăng nhập hoặc Mật khẩu!',
  'confirm': 'Xác nhận',
  'back': 'Quay lại',
  'batchBrowsingConfirmation': 'Xác nhận duyệt hàng loạt?',
  'pleaseSelectCustomer': 'Vui lòng chọn khách hàng cần duyệt',
  'selectCustomer': 'Chọn khách hàng',
  'filterAndSearch': 'Bộ lọc và tìm kiếm',
  'pleaseInputKeyWord': 'Vui lòng nhập từ khóa tìm kiếm',
  'fromDate': 'Từ ngày',
  'toDate': 'Đến ngày',
  'complete': 'Hoàn thành',
  'listDrivers': 'Danh sách tài xế',
  'listCar': 'Danh sách xe',
  'detailTitle': 'Thông tin chi tiết',
  'modifyProfile': 'Thông tin tài khoản',
  'changeVehicle': 'Đổi xe',
  'notification': 'Thông báo',
  'logout': 'Đăng xuất',
  'manageDeliveryTitle': 'Quản lý chuyến',
  'cancel': 'Hủy bỏ',
  'end': 'Kết thúc',
  'tracking': 'Tracking',
  'update': 'Cập nhật',
  'deliveryDate': 'Ngày giao',
  'receivedDate': 'Ngày nhận',
  'customer': 'Khách hàng',
  'noData': 'Không có dữ liệu',
  'anErrorOccurred': 'Đã xảy ra lỗi',
  'toDay': 'Đến ngày',
  'fromDay': 'Từ ngày',
  'done': 'Kết thúc',
  'informationAccount': 'Thông tin tài khoản',

  'hintTextFieldSearch': 'Khách hàng, điều hành,...',
  'filterFollow': 'Lọc theo',
  'tripNotCreated': 'Chưa tạo chuyến',
  'receivedGoods': 'Đã nhận hàng',
  'feeApproved': 'Đã duyệt phí',
  'tripApproved': 'Đã duyệt chuyến',
  'denied': 'Đã từ chối',
  'delivered': 'Đã giao hàng',
  'noNewTripDriver': 'Hiện tại, bạn không có chuyến. Vui lòng tạo chuyến để xem thông tin',
  'history': 'Lịch sử',
  'editInformation': 'Chỉnh sửa thông tin',

  'firstNameAndLastName': 'Họ và tên',
  'birthday': 'Ngày sinh',
  'email': 'Email',
  'identityCard': 'CMND',
  'reload': 'Tải lại',
  'search': 'Tìm kiếm',
  'enterTheReasonForEndingTheTrip': 'Nhập lý do kết thúc chuyến',
  'inputNameCustomer': 'Nhập tên khách hàng',
  'viewDetail': 'Xem chi tiết',
  'flightCode': 'Mã chuyến',
  'status': 'Trạng thái',
  'transshipment': 'Tăng bo',
  'doneDelivery': 'Đã giao xong',
  'unfinished': 'Chưa hoàn thành',
  'increaseBo': 'Tăng bo'
};
